trigger: none
resources:
  pipelines:
  - pipeline: Site
    source: furyd.service-fabric-test

variables:
- group: TU-TEST

jobs:
- deployment:
  displayName: Deploy package

  pool:
    vmImage: windows-latest

  environment: sftest-test

  strategy:
    runOnce:
      deploy:
        steps:
          - powershell: 'dir env:'
            displayName: 'Print variables'

          - task: ServiceFabricDeploy@1
            displayName: Deploy app
            inputs:
              applicationPackagePath: $(Pipeline.Workspace)/package
              serviceConnectionName: $(arm.project.name)-$(arm.service.name)-$(arm.environment.name)-sf-connection