trigger: none
resources:
  pipelines:
  - pipeline: Site
    source: furyd.service-fabric-test

variables:
- group: TU-TEST

jobs:
- deployment:
  displayName: Deploy package

  pool:
    vmImage: windows-latest

  environment: sftest-test

  strategy:
    runOnce:
      deploy:
        steps:
          - powershell: 'dir env:'
            displayName: 'Print variables'

          - task: AzurePowerShell@5
            displayName: Create service connection
            inputs:
              azureSubscription: $(arm.connection)
              azurePowerShellVersion: latestVersion
              pwsh: true
              scriptType: inlineScript
              inline: |
                $connection = az devops service-endpoint show $(arm.project.name)-$(arm.service.name)-$(arm.environment.name)-sf-connection

                if($connection -ne $null){
                  Write-Host "$(arm.project.name)-$(arm.service.name)-$(arm.environment.name)-sf-connection already exists"
                  exit
                }

                Write-Host "Create $(arm.project.name)-$(arm.service.name)-$(arm.environment.name)-sf-connection"

                $test = az devops service-endpoint create --org $(arm.organisation.uri) --project $(arm.organisation.project.name) --service-endpoint-configuration build\service-fabric.service-connection.json

                $test

          # - task: ServiceFabricDeploy@1
          #   displayName: Deploy app
          #   inputs:
          #     applicationPackagePath: $(Pipeline.Workspace)/package
          #     serviceConnectionName: $(arm.project.name)-$(arm.service.name)-$(arm.environment.name)-sf-connection