trigger: none
resources:
  pipelines:
  - pipeline: Site
    source: furyd.service-fabric-test

variables:
- group: TU-TEST

jobs:
- deployment:
  displayName: Deploy package

  pool:
    vmImage: windows-latest

  environment: sftest-test

  strategy:
    runOnce:
      deploy:
        steps:
          - powershell: 'dir env:'
            displayName: 'Print variables'

          - powershell: 'Get-ChildItem -Recurse $(Pipeline.Workspace) | Select Name,FullName,Length'
            displayName: 'Print files'

          - task: ServiceFabricDeploy@1
            displayName: Deploy app
            inputs:
              applicationPackagePath: $(Pipeline.Workspace)/Site/package
              serviceConnectionName: $(arm.project.name)-$(arm.service.name)-$(arm.environment.name)-sf-connection
              #publishProfilePath: $(Pipeline.Workspace)\Site\package-artifacts\FlexibleExample.ServiceFabric\ApplicationParameters\cloud.xml
              applicationParameterPath: $(Pipeline.Workspace)\Site\package-artifacts\FlexibleExample.ServiceFabric\PublishProfiles\cloud.xml